//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

namespace MathNet.Numerics.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
#if NET45REFLECTION
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MathNet.Numerics.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
#else
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MathNet.Numerics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
#endif
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The accuracy couldn&apos;t be reached with the specified number of iterations..
        /// </summary>
        public static string AccuracyNotReached {
            get {
                return ResourceManager.GetString("AccuracyNotReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array arguments must have the same length..
        /// </summary>
        public static string ArgumentArraysSameLength {
            get {
                return ResourceManager.GetString("ArgumentArraysSameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given array has the wrong length. Should be {0}..
        /// </summary>
        public static string ArgumentArrayWrongLength {
            get {
                return ResourceManager.GetString("ArgumentArrayWrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument must be between 0 and 1..
        /// </summary>
        public static string ArgumentBetween0And1 {
            get {
                return ResourceManager.GetString("ArgumentBetween0And1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be in the range -1 &lt; x &lt; 1..
        /// </summary>
        public static string ArgumentCannotBeBetweenOneAndNegativeOne {
            get {
                return ResourceManager.GetString("ArgumentCannotBeBetweenOneAndNegativeOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be even..
        /// </summary>
        public static string ArgumentEven {
            get {
                return ResourceManager.GetString("ArgumentEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The histogram does not contain the value..
        /// </summary>
        public static string ArgumentHistogramContainsNot {
            get {
                return ResourceManager.GetString("ArgumentHistogramContainsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is expected to be between {0} and {1} (including {0} and {1})..
        /// </summary>
        public static string ArgumentInIntervalXYInclusive {
            get {
                return ResourceManager.GetString("ArgumentInIntervalXYInclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one item of {0} is a null reference (Nothing in Visual Basic)..
        /// </summary>
        public static string ArgumentItemNull {
            get {
                return ResourceManager.GetString("ArgumentItemNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than or equal to one..
        /// </summary>
        public static string ArgumentLessThanOne {
            get {
                return ResourceManager.GetString("ArgumentLessThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix dimensions must agree..
        /// </summary>
        public static string ArgumentMatrixDimensions {
            get {
                return ResourceManager.GetString("ArgumentMatrixDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix dimensions must agree: {0}..
        /// </summary>
        public static string ArgumentMatrixDimensions1 {
            get {
                return ResourceManager.GetString("ArgumentMatrixDimensions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix dimensions must agree: op1 is {0}, op2 is {1}..
        /// </summary>
        public static string ArgumentMatrixDimensions2 {
            get {
                return ResourceManager.GetString("ArgumentMatrixDimensions2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix dimensions must agree: op1 is {0}, op2 is {1}, op3 is {2}..
        /// </summary>
        public static string ArgumentMatrixDimensions3 {
            get {
                return ResourceManager.GetString("ArgumentMatrixDimensions3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested matrix does not exist..
        /// </summary>
        public static string ArgumentMatrixDoesNotExist {
            get {
                return ResourceManager.GetString("ArgumentMatrixDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The matrix indices must not be out of range of the given matrix..
        /// </summary>
        public static string ArgumentMatrixIndexOutOfRange {
            get {
                return ResourceManager.GetString("ArgumentMatrixIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must not be rank deficient..
        /// </summary>
        public static string ArgumentMatrixNotRankDeficient {
            get {
                return ResourceManager.GetString("ArgumentMatrixNotRankDeficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must not be singular..
        /// </summary>
        public static string ArgumentMatrixNotSingular {
            get {
                return ResourceManager.GetString("ArgumentMatrixNotSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must be positive definite..
        /// </summary>
        public static string ArgumentMatrixPositiveDefinite {
            get {
                return ResourceManager.GetString("ArgumentMatrixPositiveDefinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix column dimensions must agree..
        /// </summary>
        public static string ArgumentMatrixSameColumnDimension {
            get {
                return ResourceManager.GetString("ArgumentMatrixSameColumnDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix row dimensions must agree..
        /// </summary>
        public static string ArgumentMatrixSameRowDimension {
            get {
                return ResourceManager.GetString("ArgumentMatrixSameRowDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must have exactly one column..
        /// </summary>
        public static string ArgumentMatrixSingleColumn {
            get {
                return ResourceManager.GetString("ArgumentMatrixSingleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must have exactly one column and row, thus have only one cell..
        /// </summary>
        public static string ArgumentMatrixSingleColumnRow {
            get {
                return ResourceManager.GetString("ArgumentMatrixSingleColumnRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must have exactly one row..
        /// </summary>
        public static string ArgumentMatrixSingleRow {
            get {
                return ResourceManager.GetString("ArgumentMatrixSingleRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must be square..
        /// </summary>
        public static string ArgumentMatrixSquare {
            get {
                return ResourceManager.GetString("ArgumentMatrixSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must be symmetric..
        /// </summary>
        public static string ArgumentMatrixSymmetric {
            get {
                return ResourceManager.GetString("ArgumentMatrixSymmetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must be symmetric positive definite..
        /// </summary>
        public static string ArgumentMatrixSymmetricPositiveDefinite {
            get {
                return ResourceManager.GetString("ArgumentMatrixSymmetricPositiveDefinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the specified range, the exclusive maximum must be greater than the inclusive minimum..
        /// </summary>
        public static string ArgumentMaxExclusiveMustBeLargerThanMinInclusive {
            get {
                return ResourceManager.GetString("ArgumentMaxExclusiveMustBeLargerThanMinInclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the specified range, the minimum is greater than maximum..
        /// </summary>
        public static string ArgumentMinValueGreaterThanMaxValue {
            get {
                return ResourceManager.GetString("ArgumentMinValueGreaterThanMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be positive..
        /// </summary>
        public static string ArgumentMustBePositive {
            get {
                return ResourceManager.GetString("ArgumentMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must neither be infinite nor NaN..
        /// </summary>
        public static string ArgumentNotInfinityNaN {
            get {
                return ResourceManager.GetString("ArgumentNotInfinityNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must not be negative (zero is ok)..
        /// </summary>
        public static string ArgumentNotNegative {
            get {
                return ResourceManager.GetString("ArgumentNotNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a null reference (Nothing in Visual Basic)..
        /// </summary>
        public static string ArgumentNull {
            get {
                return ResourceManager.GetString("ArgumentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be odd..
        /// </summary>
        public static string ArgumentOdd {
            get {
                return ResourceManager.GetString("ArgumentOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}..
        /// </summary>
        public static string ArgumentOutOfRangeGreater {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than or equal to {1}..
        /// </summary>
        public static string ArgumentOutOfRangeGreaterEqual {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeGreaterEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be smaller than {1}..
        /// </summary>
        public static string ArgumentOutOfRangeSmaller {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeSmaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be smaller than or equal to {1}..
        /// </summary>
        public static string ArgumentOutOfRangeSmallerEqual {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeSmallerEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chosen parameter set is invalid (probably some value is out of range)..
        /// </summary>
        public static string ArgumentParameterSetInvalid {
            get {
                return ResourceManager.GetString("ArgumentParameterSetInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given expression does not represent a complex number..
        /// </summary>
        public static string ArgumentParseComplexNumber {
            get {
                return ResourceManager.GetString("ArgumentParseComplexNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be positive (and not zero)..
        /// </summary>
        public static string ArgumentPositive {
            get {
                return ResourceManager.GetString("ArgumentPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size must be a Power of Two..
        /// </summary>
        public static string ArgumentPowerOfTwo {
            get {
                return ResourceManager.GetString("ArgumentPowerOfTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size must be a Power of Two in every dimension..
        /// </summary>
        public static string ArgumentPowerOfTwoEveryDimension {
            get {
                return ResourceManager.GetString("ArgumentPowerOfTwoEveryDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The range between {0} and {1} must be less than or equal to {2}..
        /// </summary>
        public static string ArgumentRangeLessEqual {
            get {
                return ResourceManager.GetString("ArgumentRangeLessEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments must be different objects..
        /// </summary>
        public static string ArgumentReferenceDifferent {
            get {
                return ResourceManager.GetString("ArgumentReferenceDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array must have exactly one dimension (and not be null)..
        /// </summary>
        public static string ArgumentSingleDimensionArray {
            get {
                return ResourceManager.GetString("ArgumentSingleDimensionArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is too large..
        /// </summary>
        public static string ArgumentTooLarge {
            get {
                return ResourceManager.GetString("ArgumentTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is too large for the current iteration limit..
        /// </summary>
        public static string ArgumentTooLargeForIterationLimit {
            get {
                return ResourceManager.GetString("ArgumentTooLargeForIterationLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type mismatch..
        /// </summary>
        public static string ArgumentTypeMismatch {
            get {
                return ResourceManager.GetString("ArgumentTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The upper bound must be strictly larger than the lower bound..
        /// </summary>
        public static string ArgumentUpperBoundMustBeLargerThanLowerBound {
            get {
                return ResourceManager.GetString("ArgumentUpperBoundMustBeLargerThanLowerBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The upper bound must be at least as large as the lower bound..
        /// </summary>
        public static string ArgumentUpperBoundMustBeLargerThanOrEqualToLowerBound {
            get {
                return ResourceManager.GetString("ArgumentUpperBoundMustBeLargerThanOrEqualToLowerBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array length must be a multiple of {0}..
        /// </summary>
        public static string ArgumentVectorLengthsMultipleOf {
            get {
                return ResourceManager.GetString("ArgumentVectorLengthsMultipleOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All vectors must have the same dimensionality..
        /// </summary>
        public static string ArgumentVectorsSameLength {
            get {
                return ResourceManager.GetString("ArgumentVectorsSameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vector must have 3 dimensions..
        /// </summary>
        public static string ArgumentVectorThreeDimensional {
            get {
                return ResourceManager.GetString("ArgumentVectorThreeDimensional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given array is too small. It must be at least {0} long..
        /// </summary>
        public static string ArrayTooSmall {
            get {
                return ResourceManager.GetString("ArrayTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big endian files are not supported..
        /// </summary>
        public static string BigEndianNotSupported {
            get {
                return ResourceManager.GetString("BigEndianNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied collection is empty..
        /// </summary>
        public static string CollectionEmpty {
            get {
                return ResourceManager.GetString("CollectionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex matrices are not supported..
        /// </summary>
        public static string ComplexMatricesNotSupported {
            get {
                return ResourceManager.GetString("ComplexMatricesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An algorithm failed to converge..
        /// </summary>
        public static string ConvergenceFailed {
            get {
                return ResourceManager.GetString("ConvergenceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sample size must be larger than the given degrees of freedom..
        /// </summary>
        public static string DegreesOfFreedomMustBeLessThanSampleSize {
            get {
                return ResourceManager.GetString("DegreesOfFreedomMustBeLessThanSampleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not implemented yet (but is planned)..
        /// </summary>
        public static string FeaturePlannedButNotImplementedYet {
            get {
                return ResourceManager.GetString("FeaturePlannedButNotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given file doesn&apos;t exist..
        /// </summary>
        public static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample points should be sorted in strictly ascending order.
        /// </summary>
        public static string Interpolation_Initialize_SamplePointsNotStrictlyAscendingOrder {
            get {
                return ResourceManager.GetString("Interpolation_Initialize_SamplePointsNotStrictlyAscendingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All sample points should be unique..
        /// </summary>
        public static string Interpolation_Initialize_SamplePointsNotUnique {
            get {
                return ResourceManager.GetString("Interpolation_Initialize_SamplePointsNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameterization for the distribution..
        /// </summary>
        public static string InvalidDistributionParameters {
            get {
                return ResourceManager.GetString("InvalidDistributionParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Left Boundary Condition..
        /// </summary>
        public static string InvalidLeftBoundaryCondition {
            get {
                return ResourceManager.GetString("InvalidLeftBoundaryCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation could not be performed because the accumulator is empty..
        /// </summary>
        public static string InvalidOperationAccumulatorEmpty {
            get {
                return ResourceManager.GetString("InvalidOperationAccumulatorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation could not be performed because the histogram is empty..
        /// </summary>
        public static string InvalidOperationHistogramEmpty {
            get {
                return ResourceManager.GetString("InvalidOperationHistogramEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough points in the distribution..
        /// </summary>
        public static string InvalidOperationHistogramNotEnoughPoints {
            get {
                return ResourceManager.GetString("InvalidOperationHistogramNotEnoughPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Samples Provided. Preparation Required..
        /// </summary>
        public static string InvalidOperationNoSamplesProvided {
            get {
                return ResourceManager.GetString("InvalidOperationNoSamplesProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid parameter was passed to a native method..
        /// </summary>
        public static string InvalidParameter {
            get {
                return ResourceManager.GetString("InvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid parameter was passed to a native method, parameter number : {0}.
        /// </summary>
        public static string InvalidParameterWithNumber {
            get {
                return ResourceManager.GetString("InvalidParameterWithNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Right Boundary Condition..
        /// </summary>
        public static string InvalidRightBoundaryCondition {
            get {
                return ResourceManager.GetString("InvalidRightBoundaryCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lag must be positive.
        /// </summary>
        public static string LagMustBePositive {
            get {
                return ResourceManager.GetString("LagMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lag must be smaller than the sample size.
        /// </summary>
        public static string LagMustBeSmallerThanTheSampleSize {
            get {
                return ResourceManager.GetString("LagMustBeSmallerThanTheSampleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddd MMM dd HH:mm:ss yyyy.
        /// </summary>
        public static string MatlabDateHeaderFormat {
            get {
                return ResourceManager.GetString("MatlabDateHeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrices can not be empty and must have at least one row and column..
        /// </summary>
        public static string MatrixCanNotBeEmpty {
            get {
                return ResourceManager.GetString("MatrixCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of columns of a matrix must be positive..
        /// </summary>
        public static string MatrixColumnsMustBePositive {
            get {
                return ResourceManager.GetString("MatrixColumnsMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must be in sparse storage format.
        /// </summary>
        public static string MatrixMustBeSparse {
            get {
                return ResourceManager.GetString("MatrixMustBeSparse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of rows of a matrix must be positive..
        /// </summary>
        public static string MatrixRowsMustBePositive {
            get {
                return ResourceManager.GetString("MatrixRowsMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of rows or columns of a matrix must be positive..
        /// </summary>
        public static string MatrixRowsOrColumnsMustBePositive {
            get {
                return ResourceManager.GetString("MatrixRowsOrColumnsMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to allocate native memory..
        /// </summary>
        public static string MemoryAllocation {
            get {
                return ResourceManager.GetString("MemoryAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 1 and 2 dimensional arrays are supported..
        /// </summary>
        public static string MoreThan2D {
            get {
                return ResourceManager.GetString("MoreThan2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data must contain at least {0} values..
        /// </summary>
        public static string MustContainAtLeast {
            get {
                return ResourceManager.GetString("MustContainAtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot contain a space. name:  {0}.
        /// </summary>
        public static string NameCannotContainASpace {
            get {
                return ResourceManager.GetString("NameCannotContainASpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a supported type..
        /// </summary>
        public static string NotSupportedType {
            get {
                return ResourceManager.GetString("NotSupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm experience a numerical break down
        ///.
        /// </summary>
        public static string NumericalBreakdown {
            get {
                return ResourceManager.GetString("NumericalBreakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two arguments can&apos;t be compared (maybe they are part of a partial ordering?).
        /// </summary>
        public static string PartialOrderException {
            get {
                return ResourceManager.GetString("PartialOrderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The integer array does not represent a valid permutation..
        /// </summary>
        public static string PermutationAsIntArrayInvalid {
            get {
                return ResourceManager.GetString("PermutationAsIntArrayInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sampler&apos;s proposal distribution is not upper bounding the target density..
        /// </summary>
        public static string ProposalDistributionNoUpperBound {
            get {
                return ResourceManager.GetString("ProposalDistributionNoUpperBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A regression of the requested order requires at least {0} samples. Only {1} samples have been provided. .
        /// </summary>
        public static string RegressionNotEnoughSamples {
            get {
                return ResourceManager.GetString("RegressionNotEnoughSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The algorithm has failed, exceeded the number of iterations allowed or there is no root within the provided bounds..
        /// </summary>
        public static string RootFindingFailed {
            get {
                return ResourceManager.GetString("RootFindingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The algorithm has failed, exceeded the number of iterations allowed or there is no root within the provided bounds. Consider to use RobustNewtonRaphson instead..
        /// </summary>
        public static string RootFindingFailedRecommendRobustNewtonRaphson {
            get {
                return ResourceManager.GetString("RootFindingFailedRecommendRobustNewtonRaphson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lower and upper bounds must bracket a single root..
        /// </summary>
        public static string RootMustBeBracketedByBounds {
            get {
                return ResourceManager.GetString("RootMustBeBracketedByBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The algorithm ended without root in the range..
        /// </summary>
        public static string RootNotFound {
            get {
                return ResourceManager.GetString("RootNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of rows must greater than or equal to the number of columns..
        /// </summary>
        public static string RowsLessThanColumns {
            get {
                return ResourceManager.GetString("RowsLessThanColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All sample vectors must have the same length. However, vectors with disagreeing length {0} and {1} have been provided. A sample with index i is given by the value at index i of each provided vector..
        /// </summary>
        public static string SampleVectorsSameLength {
            get {
                return ResourceManager.GetString("SampleVectorsSameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U is singular, and the inversion could not be completed..
        /// </summary>
        public static string SingularUMatrix {
            get {
                return ResourceManager.GetString("SingularUMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U is singular, and the inversion could not be completed. The {0}-th diagonal element of the factor U is zero..
        /// </summary>
        public static string SingularUMatrixWithElement {
            get {
                return ResourceManager.GetString("SingularUMatrixWithElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The singular vectors were not computed..
        /// </summary>
        public static string SingularVectorsNotComputed {
            get {
                return ResourceManager.GetString("SingularVectorsNotComputed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This special case is not supported yet (but is planned)..
        /// </summary>
        public static string SpecialCasePlannedButNotImplementedYet {
            get {
                return ResourceManager.GetString("SpecialCasePlannedButNotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given stop criterion already exist in the collection..
        /// </summary>
        public static string StopCriterionDuplicate {
            get {
                return ResourceManager.GetString("StopCriterionDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no stop criterion in the collection..
        /// </summary>
        public static string StopCriterionMissing {
            get {
                return ResourceManager.GetString("StopCriterionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String parameter cannot be empty or null..
        /// </summary>
        public static string StringNullOrEmpty {
            get {
                return ResourceManager.GetString("StringNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We only support sparse matrix with less than int.MaxValue elements..
        /// </summary>
        public static string TooManyElements {
            get {
                return ResourceManager.GetString("TooManyElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The moment of the distribution is undefined..
        /// </summary>
        public static string UndefinedMoment {
            get {
                return ResourceManager.GetString("UndefinedMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user defined provider has not been specified..
        /// </summary>
        public static string UserDefinedProviderNotSpecified {
            get {
                return ResourceManager.GetString("UserDefinedProviderNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User work buffers are not supported by this provider..
        /// </summary>
        public static string UserWorkBufferNotSupported {
            get {
                return ResourceManager.GetString("UserWorkBufferNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vectors can not be empty and must have at least one element..
        /// </summary>
        public static string VectorCanNotBeEmpty {
            get {
                return ResourceManager.GetString("VectorCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given work array is too small. Check work[0] for the corret size..
        /// </summary>
        public static string WorkArrayTooSmall {
            get {
                return ResourceManager.GetString("WorkArrayTooSmall", resourceCulture);
            }
        }
    }
}
