//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathNet.Numerics.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MathNet.Numerics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array arguments must have the same length..
        /// </summary>
        internal static string ArgumentArraysSameLength {
            get {
                return ResourceManager.GetString("ArgumentArraysSameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given array is the wrong length. Should be {0}..
        /// </summary>
        internal static string ArgumentArrayWrongLength {
            get {
                return ResourceManager.GetString("ArgumentArrayWrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument must be between 0 and 1..
        /// </summary>
        internal static string ArgumentBetween0And1 {
            get {
                return ResourceManager.GetString("ArgumentBetween0And1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be in the range -1 &lt; x &lt; 1..
        /// </summary>
        internal static string ArgumentCannotBeBetweenOneAndNegativeOne {
            get {
                return ResourceManager.GetString("ArgumentCannotBeBetweenOneAndNegativeOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be even..
        /// </summary>
        internal static string ArgumentEven {
            get {
                return ResourceManager.GetString("ArgumentEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The histogram does not contains the value..
        /// </summary>
        internal static string ArgumentHistogramContainsNot {
            get {
                return ResourceManager.GetString("ArgumentHistogramContainsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is expected to be between {0} and {1} (including {0} and {1})..
        /// </summary>
        internal static string ArgumentInIntervalXYInclusive {
            get {
                return ResourceManager.GetString("ArgumentInIntervalXYInclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one item of {0} is a null reference (Nothing in Visual Basic)..
        /// </summary>
        internal static string ArgumentItemNull {
            get {
                return ResourceManager.GetString("ArgumentItemNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than or equal to one..
        /// </summary>
        internal static string ArgumentLessThanOne {
            get {
                return ResourceManager.GetString("ArgumentLessThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to han the given upper bound..
        /// </summary>
        internal static string ArgumentLowerBoundLargerThanUpperBound {
            get {
                return ResourceManager.GetString("ArgumentLowerBoundLargerThanUpperBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix dimensions must agree..
        /// </summary>
        internal static string ArgumentMatrixDimensions {
            get {
                return ResourceManager.GetString("ArgumentMatrixDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix dimensions must agree: {0}..
        /// </summary>
        internal static string ArgumentMatrixDimensions1 {
            get {
                return ResourceManager.GetString("ArgumentMatrixDimensions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix dimensions must agree: op1 is {0}, op2 is {1}..
        /// </summary>
        internal static string ArgumentMatrixDimensions2 {
            get {
                return ResourceManager.GetString("ArgumentMatrixDimensions2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix dimensions must agree: op1 is {0}, op2 is {1}, op3 is {2}..
        /// </summary>
        internal static string ArgumentMatrixDimensions3 {
            get {
                return ResourceManager.GetString("ArgumentMatrixDimensions3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested matrix does not exist..
        /// </summary>
        internal static string ArgumentMatrixDoesNotExist {
            get {
                return ResourceManager.GetString("ArgumentMatrixDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The matrix indices must not be out of range of the given matrix..
        /// </summary>
        internal static string ArgumentMatrixIndexOutOfRange {
            get {
                return ResourceManager.GetString("ArgumentMatrixIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must not be rank deficient..
        /// </summary>
        internal static string ArgumentMatrixNotRankDeficient {
            get {
                return ResourceManager.GetString("ArgumentMatrixNotRankDeficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must not be singular..
        /// </summary>
        internal static string ArgumentMatrixNotSingular {
            get {
                return ResourceManager.GetString("ArgumentMatrixNotSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must be positive definite..
        /// </summary>
        internal static string ArgumentMatrixPositiveDefinite {
            get {
                return ResourceManager.GetString("ArgumentMatrixPositiveDefinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix column dimensions must agree..
        /// </summary>
        internal static string ArgumentMatrixSameColumnDimension {
            get {
                return ResourceManager.GetString("ArgumentMatrixSameColumnDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix row dimensions must agree..
        /// </summary>
        internal static string ArgumentMatrixSameRowDimension {
            get {
                return ResourceManager.GetString("ArgumentMatrixSameRowDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must have exactly one column..
        /// </summary>
        internal static string ArgumentMatrixSingleColumn {
            get {
                return ResourceManager.GetString("ArgumentMatrixSingleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must have exactly one column and row, thus have only one cell..
        /// </summary>
        internal static string ArgumentMatrixSingleColumnRow {
            get {
                return ResourceManager.GetString("ArgumentMatrixSingleColumnRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must have exactly one row..
        /// </summary>
        internal static string ArgumentMatrixSingleRow {
            get {
                return ResourceManager.GetString("ArgumentMatrixSingleRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must be square..
        /// </summary>
        internal static string ArgumentMatrixSquare {
            get {
                return ResourceManager.GetString("ArgumentMatrixSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must be symmetric..
        /// </summary>
        internal static string ArgumentMatrixSymmetric {
            get {
                return ResourceManager.GetString("ArgumentMatrixSymmetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must be symmetric positive definite..
        /// </summary>
        internal static string ArgumentMatrixSymmetricPositiveDefinite {
            get {
                return ResourceManager.GetString("ArgumentMatrixSymmetricPositiveDefinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the specified range, the minimum is greater than maximum..
        /// </summary>
        internal static string ArgumentMinValueGreaterThanMaxValue {
            get {
                return ResourceManager.GetString("ArgumentMinValueGreaterThanMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be positive..
        /// </summary>
        internal static string ArgumentMustBePositive {
            get {
                return ResourceManager.GetString("ArgumentMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must neither be infinite nor NaN..
        /// </summary>
        internal static string ArgumentNotInfinityNaN {
            get {
                return ResourceManager.GetString("ArgumentNotInfinityNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must not be negative (zero is ok)..
        /// </summary>
        internal static string ArgumentNotNegative {
            get {
                return ResourceManager.GetString("ArgumentNotNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a null reference (Nothing in Visual Basic)..
        /// </summary>
        internal static string ArgumentNull {
            get {
                return ResourceManager.GetString("ArgumentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be odd..
        /// </summary>
        internal static string ArgumentOdd {
            get {
                return ResourceManager.GetString("ArgumentOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}..
        /// </summary>
        internal static string ArgumentOutOfRangeGreater {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than or equal to {1}..
        /// </summary>
        internal static string ArgumentOutOfRangeGreaterEqual {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeGreaterEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chosen parameter set is invalid (probably some value is out of range)..
        /// </summary>
        internal static string ArgumentParameterSetInvalid {
            get {
                return ResourceManager.GetString("ArgumentParameterSetInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given expression does not represent a complex number..
        /// </summary>
        internal static string ArgumentParseComplexNumber {
            get {
                return ResourceManager.GetString("ArgumentParseComplexNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be positive (and not zero)..
        /// </summary>
        internal static string ArgumentPositive {
            get {
                return ResourceManager.GetString("ArgumentPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size must be a Power of Two..
        /// </summary>
        internal static string ArgumentPowerOfTwo {
            get {
                return ResourceManager.GetString("ArgumentPowerOfTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size must be a Power of Two in every dimension..
        /// </summary>
        internal static string ArgumentPowerOfTwoEveryDimension {
            get {
                return ResourceManager.GetString("ArgumentPowerOfTwoEveryDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The range between {0} and {1} must be less than or equal to {2}..
        /// </summary>
        internal static string ArgumentRangeLessEqual {
            get {
                return ResourceManager.GetString("ArgumentRangeLessEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments must be different objects..
        /// </summary>
        internal static string ArgumentReferenceDifferent {
            get {
                return ResourceManager.GetString("ArgumentReferenceDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array must have exactly one dimension (and not be null)..
        /// </summary>
        internal static string ArgumentSingleDimensionArray {
            get {
                return ResourceManager.GetString("ArgumentSingleDimensionArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is too large..
        /// </summary>
        internal static string ArgumentTooLarge {
            get {
                return ResourceManager.GetString("ArgumentTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is too large for the current iteration limit..
        /// </summary>
        internal static string ArgumentTooLargeForIterationLimit {
            get {
                return ResourceManager.GetString("ArgumentTooLargeForIterationLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type mismatch..
        /// </summary>
        internal static string ArgumentTypeMismatch {
            get {
                return ResourceManager.GetString("ArgumentTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array length must be a multiple of {0}..
        /// </summary>
        internal static string ArgumentVectorLengthsMultipleOf {
            get {
                return ResourceManager.GetString("ArgumentVectorLengthsMultipleOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All vectors must have the same dimensionality..
        /// </summary>
        internal static string ArgumentVectorsSameLength {
            get {
                return ResourceManager.GetString("ArgumentVectorsSameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vector must have 3 dimensions..
        /// </summary>
        internal static string ArgumentVectorThreeDimensional {
            get {
                return ResourceManager.GetString("ArgumentVectorThreeDimensional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given array is too small. It must be at least {0} long..
        /// </summary>
        internal static string ArrayTooSmall {
            get {
                return ResourceManager.GetString("ArrayTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big endian files are not supported..
        /// </summary>
        internal static string BigEndianNotSupported {
            get {
                return ResourceManager.GetString("BigEndianNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied collection is empty..
        /// </summary>
        internal static string CollectionEmpty {
            get {
                return ResourceManager.GetString("CollectionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex matrices are not supported..
        /// </summary>
        internal static string ComplexMatricesNotSupported {
            get {
                return ResourceManager.GetString("ComplexMatricesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An algorithm failed to converge..
        /// </summary>
        internal static string ConvergenceFailed {
            get {
                return ResourceManager.GetString("ConvergenceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not implemented yet (but is planned)..
        /// </summary>
        internal static string FeaturePlannedButNotImplementedYet {
            get {
                return ResourceManager.GetString("FeaturePlannedButNotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given file doesn&apos;t exist..
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample points should be sorted in strictly ascending order.
        /// </summary>
        internal static string Interpolation_Initialize_SamplePointsNotStrictlyAscendingOrder {
            get {
                return ResourceManager.GetString("Interpolation_Initialize_SamplePointsNotStrictlyAscendingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All sample points should be unique..
        /// </summary>
        internal static string Interpolation_Initialize_SamplePointsNotUnique {
            get {
                return ResourceManager.GetString("Interpolation_Initialize_SamplePointsNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameterization for the distribution..
        /// </summary>
        internal static string InvalidDistributionParameters {
            get {
                return ResourceManager.GetString("InvalidDistributionParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Left Boundary Condition..
        /// </summary>
        internal static string InvalidLeftBoundaryCondition {
            get {
                return ResourceManager.GetString("InvalidLeftBoundaryCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation could not be performed because the accumulator is empty..
        /// </summary>
        internal static string InvalidOperationAccumulatorEmpty {
            get {
                return ResourceManager.GetString("InvalidOperationAccumulatorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation could not be performed because the histogram is empty..
        /// </summary>
        internal static string InvalidOperationHistogramEmpty {
            get {
                return ResourceManager.GetString("InvalidOperationHistogramEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough points in the distribution..
        /// </summary>
        internal static string InvalidOperationHistogramNotEnoughPoints {
            get {
                return ResourceManager.GetString("InvalidOperationHistogramNotEnoughPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Samples Provided. Preparation Required..
        /// </summary>
        internal static string InvalidOperationNoSamplesProvided {
            get {
                return ResourceManager.GetString("InvalidOperationNoSamplesProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Right Boundary Condition..
        /// </summary>
        internal static string InvalidRightBoundaryCondition {
            get {
                return ResourceManager.GetString("InvalidRightBoundaryCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddd MMM dd HH:mm:ss yyyy.
        /// </summary>
        internal static string MatlabDateHeaderFormat {
            get {
                return ResourceManager.GetString("MatlabDateHeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of columns of a matrix must be positive..
        /// </summary>
        internal static string MatrixColumnsMustBePositive {
            get {
                return ResourceManager.GetString("MatrixColumnsMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of rows of a matrix must be positive..
        /// </summary>
        internal static string MatrixRowsMustBePositive {
            get {
                return ResourceManager.GetString("MatrixRowsMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of rows or columns of a matrix must be positive..
        /// </summary>
        internal static string MatrixRowsOrColumnsMustBePositive {
            get {
                return ResourceManager.GetString("MatrixRowsOrColumnsMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 1 and 2 dimensional arrays are supported..
        /// </summary>
        internal static string MoreThan2D {
            get {
                return ResourceManager.GetString("MoreThan2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data must contain at least {0} values..
        /// </summary>
        internal static string MustContainAtLeast {
            get {
                return ResourceManager.GetString("MustContainAtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot contain a space. name:  {0}.
        /// </summary>
        internal static string NameCannotContainASpace {
            get {
                return ResourceManager.GetString("NameCannotContainASpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a supported type..
        /// </summary>
        internal static string NotSupportedType {
            get {
                return ResourceManager.GetString("NotSupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two arguments can&apos;t be compared (maybe they are part of a partial ordering?).
        /// </summary>
        internal static string PartialOrderException {
            get {
                return ResourceManager.GetString("PartialOrderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The integer array does not represent a valid permutation..
        /// </summary>
        internal static string PermutationAsIntArrayInvalid {
            get {
                return ResourceManager.GetString("PermutationAsIntArrayInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sampler&apos;s proposal distribution is not upper bounding the target density..
        /// </summary>
        internal static string ProposalDistributionNoUpperBound {
            get {
                return ResourceManager.GetString("ProposalDistributionNoUpperBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of rows must greater than or equal to the number of columns..
        /// </summary>
        internal static string RowsLessThanColumns {
            get {
                return ResourceManager.GetString("RowsLessThanColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The singular vectors were not computed..
        /// </summary>
        internal static string SingularVectorsNotComputed {
            get {
                return ResourceManager.GetString("SingularVectorsNotComputed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This special case is not supported yet (but is planned)..
        /// </summary>
        internal static string SpecialCasePlannedButNotImplementedYet {
            get {
                return ResourceManager.GetString("SpecialCasePlannedButNotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given stop criterium already exist in the collection..
        /// </summary>
        internal static string StopCriteriumDuplicate {
            get {
                return ResourceManager.GetString("StopCriteriumDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no stop criterium in the collection..
        /// </summary>
        internal static string StopCriteriumMissing {
            get {
                return ResourceManager.GetString("StopCriteriumMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String parameter cannot be empty or null..
        /// </summary>
        internal static string StringNullOrEmpty {
            get {
                return ResourceManager.GetString("StringNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We only support sparse matrix with less than int.MaxValue elements..
        /// </summary>
        internal static string TooManyElements {
            get {
                return ResourceManager.GetString("TooManyElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The moment of the distribution is undefined..
        /// </summary>
        internal static string UndefinedMoment {
            get {
                return ResourceManager.GetString("UndefinedMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user defined provider has not been specified..
        /// </summary>
        internal static string UserDefinedProviderNotSpecified {
            get {
                return ResourceManager.GetString("UserDefinedProviderNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given work array is too small. Check work[0] for the corret size..
        /// </summary>
        internal static string WorkArrayTooSmall {
            get {
                return ResourceManager.GetString("WorkArrayTooSmall", resourceCulture);
            }
        }
    }
}
